#!/bin/bash

userName="game"
groupName="game"

dataPath="/data"
installPath="${dataPath}/game"
savesPath="${configPath}/saves/"

updateCmd="steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir ${installPath} +login anonymous +app_update 556450 +quit"

check_user() {
    if id -u ${userName} >/dev/null 2>&1; then
        echo "User is exist..."
    else
        echo "User is not exist, create it..."
        groupadd ${groupName}
        useradd -m -g ${groupName} ${userName}
    fi

    if [ ! "$(id -u ${userName})" -eq "$USER_ID" ]; then
        usermod -o -u "$USER_ID" ${userName}
        echo "User id set to ${USER_ID}"
    fi

    if [ ! "$(id -g ${groupName})" -eq "$GROUP_ID" ]; then
        groupmod -o -g "$GROUP_ID" ${groupName}
        echo "User group set to ${GROUP_ID}"
    fi
    echo "User checked ok..."
}

check_dir() {
    if [ ! -d ${dataPath} ]; then
        echo "Data dir is not exist, create it..."
        mkdir -p ${dataPath}
        mkdir -p ${savesPath}
    else
        echo "Data dir is exist..."
    fi

    local q=$(ls -l ${dataPath}|sed -n '2p' |awk -F " " '{print $3}')
    if [ "${q}"x = "${userName}"x ]; then
        echo "Permission is ok..."
    else
        echo "Permission is bad, change it..."
        chown ${userName}:${groupName} -R ${dataPath}
    fi
    echo "Dir checked ok..."
}

update_server() {
    check_user
    check_dir
    su - ${userName} -s /bin/bash -c "${updateCmd}"
}
